# Generated by Django 5.0.7 on 2024-07-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=15, unique=True)),
                ('propuesta', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
