# Generated by Django 5.0.7 on 2024-07-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listas',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
