# Generated by Django 5.0.7 on 2024-07-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_alter_listas_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listas',
            name='propuesta',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
