# Generated by Django 5.0.7 on 2024-07-14 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_remove_candidato_lista_remove_dignidad_nombre_and_more'),
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(default='', upload_to='candidatos'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='listas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.listas'),
        ),
    ]
