# Generated by Django 5.0.7 on 2024-07-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_candidato_foto_alter_candidato_listas'),
        ('estudiante', '0003_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estudiante.estudiante'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='dignidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidato.dignidad'),
        ),
    ]
