# Generated by Django 5.0.7 on 2024-07-23 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0003_alter_curso_nivel'),
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('listas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.listas')),
            ],
        ),
    ]
